# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default   # 你的 self-hosted agent pool

steps:
- script: |
    wsl bash -c "cd /home/mika/test_django && source venv/bin/activate && cd mysite && python manage.py migrate && nohup python manage.py runserver 0.0.0.0:8000 > nohup.out 2>&1 &"
  displayName: 'Deploy Django backend in WSL'






