version: "3.8"

services:
  django:
    container_name: django
    build:
      context: ../mysite
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network

  react:
    container_name: react-soft-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app_network
    depends_on:
      - django

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - django
      - react
    networks:
      - app_network

networks:
  app_network:
    driver: bridge